name: Remote Bazel Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download bb cli
        run: |
          bazel build cli

      - name: Setup git env
        run: |
          git checkout master
          git checkout -

      - name: Test
        run: |
          $PWD/bazel-bin/cli/cmd/bb/bb_/bb --verbose=1 remote test //... \
            --config=linux-workflows --config=race \
            --remote_executor=grpcs://buildbuddy.buildbuddy.io \
            --test_tag_filters=-performance,-webdriver,-docker,-bare \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}
