name: Remote Bazel Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download bb cli
        run: |
          cli/install.sh

      - name: Test
        run: |
          bb remote test //... \
            --config=linux-workflows --config=race \
            --test_tag_filters=-performance,-webdriver,-docker,-bare \
            --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_ORG_API_KEY }}
