name: "release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Git branch to checkout."
        required: true
        default: "master"
        type: string
      version_tag:
        description: "Version to tag release artifacts."
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.vars.outputs.ref }}
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Configure variables
        id: vars
        run: |
          # Configure repo based on pushed tag if set
          if [ ${{ github.event_name }} = 'push' ]; then
            ref="${GITHUB_REF}"
            tag=${GITHUB_REF/refs\/tags\//}
          else
            # Otherwise the workflow must have been manually triggered with inputs
            ref="${{ inputs.release_branch }}"
            tag="${{ inputs.version_tag }}"
          fi
          echo "ref=$ref" >> $GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT

  create-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'release skip')"
    needs: setup
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.BUILDBUDDY_GITHUB_USER_TOKEN }}"
          prerelease: false
          draft: true
          automatic_release_tag: ${{ needs.setup.outputs.tag }}